[tasks.build]
command = "cargo"
args = ["build"]

[tasks.dev]
command = "cargo"
args = ["run"]

[tasks.test]
command = "cargo"
args = ["nextest", "run"]

[tasks.watch]
command = "cargo"
args = ["watch", "-x", "build", "-x", "test", "-x", "run"]
